import { contextBridge, ipcRenderer } from 'electron'
import { CH, type AppState, type AudioDevice, type LiveStats, type AxiApi, type StreamSettingsView, type MaskRect, type GameAudioPluginView, type AudioLevels, type UpdateStatus, type ToastPayload, type DiscordTestResult, type AudioTestResult, type DiagnosticsResult, type RecordStartResult, type RecordStopResult, type ChooseDirResult, type OpenResult, type WebcamConfig, type WebcamProps, type SetHotkeyResult } from '../shared/state.js'
import type { PttBinding, PttCaptureResult } from '../shared/keys.js'
import type { Binding, HotkeyId } from '../shared/hotkeys.js'

const sub = <T,>(channel: string, cb: (p: T) => void) => {
  const listener = (_e: unknown, p: T) => cb(p)
  ipcRenderer.on(channel, listener)
  return () => ipcRenderer.removeListener(channel, listener)
}

const api: AxiApi = {
  getInitialState: () => ipcRenderer.invoke(CH.getInitialState) as Promise<AppState>,
  provision: (target) => ipcRenderer.invoke(CH.provision, target) as Promise<void>,
  getCaptureTargets: () => ipcRenderer.invoke(CH.getCaptureTargets) as Promise<import('../shared/state.js').CaptureTargetOption[]>,
  cancelCaptureSelection: () => ipcRenderer.invoke(CH.cancelCaptureSelection) as Promise<void>,
  goLive: (title) => ipcRenderer.invoke(CH.goLive, title) as Promise<void>,
  stopStream: () => ipcRenderer.invoke(CH.stopStream) as Promise<void>,
  repairCapture: () => ipcRenderer.invoke(CH.repairCapture) as Promise<void>,
  switchSource: () => ipcRenderer.invoke(CH.switchSource) as Promise<void>,
  connectYouTube: () => ipcRenderer.invoke(CH.connectYouTube) as Promise<void>,
  disconnectYouTube: () => ipcRenderer.invoke(CH.disconnectYouTube) as Promise<void>,
  getSettings: () => ipcRenderer.invoke(CH.getSettings) as Promise<StreamSettingsView>,
  saveSettings: (p) => ipcRenderer.invoke(CH.saveSettings, p) as Promise<StreamSettingsView>,
  previewTitle: (t) => ipcRenderer.invoke(CH.previewTitle, t) as Promise<string>,
  getAudioDevices: () => ipcRenderer.invoke(CH.getAudioDevices) as Promise<AudioDevice[]>,
  setDesktopEnabled: (enabled) => ipcRenderer.invoke(CH.setDesktopEnabled, enabled) as Promise<void>,
  setMicEnabled: (enabled) => ipcRenderer.invoke(CH.setMicEnabled, enabled) as Promise<void>,
  setMicDevice: (deviceId) => ipcRenderer.invoke(CH.setMicDevice, deviceId) as Promise<void>,
  getDesktopDevices: () => ipcRenderer.invoke(CH.getDesktopDevices) as Promise<AudioDevice[]>,
  setDesktopDevice: (deviceId) => ipcRenderer.invoke(CH.setDesktopDevice, deviceId) as Promise<void>,
  setMasks: (masks) => ipcRenderer.invoke(CH.setMasks, masks) as Promise<void>,
  windowMinimize: () => ipcRenderer.invoke(CH.windowMinimize) as Promise<void>,
  windowToggleMaximize: () => ipcRenderer.invoke(CH.windowToggleMaximize) as Promise<void>,
  windowClose: () => ipcRenderer.invoke(CH.windowClose) as Promise<void>,
  getGameAudioPluginStatus: () => ipcRenderer.invoke(CH.getGameAudioPluginStatus) as Promise<GameAudioPluginView>,
  installGameAudioPlugin: () => ipcRenderer.invoke(CH.installGameAudioPlugin) as Promise<void>,
  setMaskStyle: (style) => ipcRenderer.invoke(CH.setMaskStyle, style) as Promise<void>,
  installBlurPlugin: () => ipcRenderer.invoke(CH.installBlurPlugin) as Promise<void>,
  relaunchApp: () => ipcRenderer.invoke(CH.relaunchApp) as Promise<void>,
  setGameAudioApps: (apps) => ipcRenderer.invoke(CH.setGameAudioApps, apps) as Promise<void>,
  getGameAudioApps: () => ipcRenderer.invoke(CH.getGameAudioApps) as Promise<AudioDevice[]>,
  fitWindowToCapture: () => ipcRenderer.invoke(CH.fitWindowToCapture) as Promise<void>,
  testDiscordWebhook: () => ipcRenderer.invoke(CH.testDiscordWebhook) as Promise<DiscordTestResult>,
  recordAudioTest: () => ipcRenderer.invoke(CH.recordAudioTest) as Promise<AudioTestResult>,
  setPttEnabled: (enabled) => ipcRenderer.invoke(CH.setPttEnabled, enabled) as Promise<void>,
  setPttBinding: (b: PttBinding) => ipcRenderer.invoke(CH.setPttBinding, b) as Promise<void>,
  capturePttKey: () => ipcRenderer.invoke(CH.capturePttKey) as Promise<PttCaptureResult>,
  unlockPassthrough: () => ipcRenderer.invoke(CH.unlockPassthrough) as Promise<{ ok: boolean; error?: string }>,
  setMasksVisible: (visible) => ipcRenderer.invoke(CH.setMasksVisible, visible) as Promise<void>,
  checkForUpdates: () => ipcRenderer.invoke(CH.updatesCheck) as Promise<void>,
  installUpdate: () => ipcRenderer.invoke(CH.updatesInstall) as Promise<void>,
  appVersion: () => ipcRenderer.invoke(CH.appVersion) as Promise<string>,
  getWhatsNew: () => ipcRenderer.invoke(CH.getWhatsNew) as Promise<{ version: string; notes: string | null }>,
  setLastSeenVersion: (v: string) => ipcRenderer.invoke(CH.setLastSeenVersion, v) as Promise<void>,
  copyToClipboard: (text: string) => ipcRenderer.invoke(CH.copyToClipboard, text) as Promise<boolean>,
  openExternalUrl: (url: string) => ipcRenderer.invoke(CH.openExternalUrl, url) as Promise<boolean>,
  exportDiagnostics: () => ipcRenderer.invoke(CH.exportDiagnostics) as Promise<DiagnosticsResult>,
  startRecording: () => ipcRenderer.invoke(CH.startRecording) as Promise<RecordStartResult>,
  stopRecording: () => ipcRenderer.invoke(CH.stopRecording) as Promise<RecordStopResult>,
  chooseRecordDir: () => ipcRenderer.invoke(CH.chooseRecordDir) as Promise<ChooseDirResult>,
  openRecording: (path: string) => ipcRenderer.invoke(CH.openRecording, path) as Promise<OpenResult>,
  dismissSummary: () => ipcRenderer.invoke(CH.dismissSummary) as Promise<void>,
  setWebcam: (p) => ipcRenderer.invoke(CH.setWebcam, p) as Promise<void>,
  setQuality: (p) => ipcRenderer.invoke(CH.setQuality, p) as Promise<void>,
  setHotkey: (id: HotkeyId, binding: Binding | null) => ipcRenderer.invoke(CH.setHotkey, id, binding) as Promise<SetHotkeyResult>,
  getWebcamDevices: () => ipcRenderer.invoke(CH.getWebcamDevices) as Promise<AudioDevice[]>,
  getWebcamProps: () => ipcRenderer.invoke(CH.getWebcamProps) as Promise<WebcamProps>,
  onState: (cb) => sub<Partial<AppState>>(CH.evtState, cb),
  onStats: (cb) => sub<LiveStats>(CH.evtStats, cb),
  onPreview: (cb) => sub<string>(CH.evtPreview, cb),
  onCaptureChanged: (cb) => sub<void>(CH.evtCaptureChanged, () => cb()),
  onAudioLevels: (cb) => sub<AudioLevels>(CH.evtAudioLevels, cb),
  onUpdateStatus: (cb) => sub<UpdateStatus>(CH.evtUpdateStatus, cb),
  onToast: (cb) => sub<ToastPayload>(CH.evtToast, cb),
}
contextBridge.exposeInMainWorld('axi', api)
