// Extract one `## Version vX.Y.Z — <date>` section out of RELEASE_NOTES.md.
// The release workflow uses this as the GitHub Release body and treats a
// missing section as a hard failure, so a release can never go out with
// autogenerated notes.
//
//   node scripts/release-notes.mjs vX.Y.Z
import { readFile } from 'node:fs/promises'
import { fileURLToPath, pathToFileURL } from 'node:url'
import { dirname, join } from 'node:path'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')

/** @param {string} md @param {string} tag @returns {string} */
export function extractNotes(md, tag) {
  const out = []
  let capturing = false
  for (const line of md.split('\n')) {
    const header = line.match(/^## Version (v\S+)/)
    if (header) {
      if (capturing) break
      if (header[1] === tag) capturing = true
      continue
    }
    if (capturing) out.push(line)
  }
  return out.join('\n').trim()
}

// Only run the CLI when invoked directly, so the self-test can import the
// function without triggering a process.exit.
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const tag = process.argv[2]
  if (!tag) {
    console.error('usage: node scripts/release-notes.mjs vX.Y.Z')
    process.exit(1)
  }
  const md = await readFile(join(root, 'RELEASE_NOTES.md'), 'utf8')
  const notes = extractNotes(md, tag)
  if (!notes) {
    console.error(`No RELEASE_NOTES.md section found for ${tag}. Add a '## Version ${tag} — <date>' entry and re-run.`)
    process.exit(1)
  }
  process.stdout.write(notes + '\n')
}
